# Checkov configuration for CloudCrew dev environment.
# Suppressions are dev-only relaxations — revisit for staging/production.

skip-check:
  # --- Lambda (dev doesn't need DLQ, concurrency limits, code signing, KMS) ---
  - CKV_AWS_115  # Lambda concurrent execution limit (not needed in dev)
  - CKV_AWS_116  # Lambda DLQ (not needed in dev)
  - CKV_AWS_173  # Lambda env vars KMS encryption (no secrets in env vars)
  - CKV_AWS_272  # Lambda code signing (overkill for dev)

  # --- CloudWatch Logs (dev uses short retention, no KMS) ---
  - CKV_AWS_158  # CloudWatch log groups KMS encryption (overkill for dev)
  - CKV_AWS_338  # CloudWatch log groups 1-year retention (14 days for dev)

  # --- Networking (dev uses public subnets — no NAT Gateway cost) ---
  - CKV_AWS_130  # Subnets assign public IP (intentional for ECS Fargate dev)

  # --- DynamoDB (dev uses AWS-managed KMS, no autoscaling) ---
  - CKV_AWS_119  # DynamoDB customer-managed KMS (AWS-managed is sufficient)

  # --- S3 (dev doesn't need access logging, lifecycle, notifications) ---
  - CKV_AWS_50   # X-Ray tracing on Lambda (not needed in dev)
  - CKV_AWS_51   # ECR repository encryption with KMS CMK
  - CKV_AWS_336  # ECR repository KMS encryption (AES256 is sufficient)

  # --- ECS (dev relaxations) ---
  - CKV_AWS_117  # ECS task definition encryption in transit (FARGATE handles this)
  - CKV_AWS_136  # ECS task definition health check
  - CKV_AWS_237  # ECS task definition readonly root filesystem

  # --- API Gateway (auth deferred to M5/Cognito, logging not needed in dev) ---
  - CKV_AWS_59   # API Gateway method authorization (deferred to M5 Cognito)
  - CKV_AWS_73   # API Gateway stage WAF (not needed in dev)
  - CKV_AWS_76   # API Gateway stage logging (not needed in dev)
  - CKV_AWS_120  # API Gateway caching (not needed in dev)

  # --- Step Functions ---
  - CKV_AWS_284  # State Machine X-Ray tracing (not needed in dev)
